import type { Command } from "commander";
import { bold, cmd, dim, file, green, minus, plus, yellow } from "../format.js";
import { createJudgeScope, verifyJudgeRecord } from "../judge-enforcement.js";
import {
  captureJudgeCatchUpSnapshot,
  captureJudgeSnapshot,
  checkJudgeReviewCurrentState,
  pruneJudgeSnapshots,
} from "../judge-snapshot.js";
import { runJudgeDisable, runJudgeEnable, runJudgeStatus } from "../judge.js";
import { addCommon, ln, log, mark, normalizeOptions, printAgentModels, printAgentWarnings } from "./shared.js";

export function registerJudge(program: Command): void {
  const judge = program.command("judge").description("Manage the optional akrctx judge subagent.");

  addCommon(
    judge
      .command("enable")
      .description("Enable the judge and install agent files for the installed targets.")
      .addHelpText(
        "after",
        [
          "",
          "Generates a judge agent file for each installed target:",
          "  Claude Code  →  .claude/agents/akrctx-judge.md",
          "  Copilot      →  .github/agents/akrctx-judge.agent.md",
          "  Codex        →  .codex/agents/akrctx-judge.toml",
          "  Pi           →  not supported (skipped)",
          "",
          "The model comes from the config, per host, and is regenerated by upgrade:",
          "",
          "  akrctx config set agents.judge.model.claude <model-id>",
          "  akrctx config set agents.judge.model.codex  <model-id>",
          "  akrctx config set agents.judge.model.copilot <model-id>",
          "",
          "Identifiers are platform-specific and change over time. akrctx checks the",
          "shape and warns about an unfamiliar one, but writes whatever you configure.",
        ].join("\n"),
      ),
    false,
  ).action(async (raw) => {
    const options = normalizeOptions(raw);
    const result = await runJudgeEnable(options);
    if (options.json) {
      console.log(JSON.stringify(result, null, 2));
      return;
    }
    const verb = options.dryRun ? "Would install" : "Installed";
    log(`${bold("Judge:")} ${options.dryRun ? yellow("would enable (dry-run)") : green("enabled")}`);
    if (result.writes.length) {
      ln();
      for (const w of result.writes) log(`  ${mark(w.kind)} ${file(w.path)}`);
    }
    if (result.skippedTargets.length) {
      ln();
      log(
        `  ${dim(`Skipped (no agent format, or not listed in agents.judge.targets): ${result.skippedTargets.join(", ")}`)}`,
      );
    }
    ln();
    log(`  ${dim(`${verb} for: ${result.installedTargets.join(", ")}`)}`);
    printAgentModels(result.models);
    printAgentWarnings(result.warnings);
  });

  addCommon(
    judge.command("disable").description("Disable the judge. Agent files are kept — remove them manually if needed."),
    false,
  ).action(async (raw) => {
    const options = normalizeOptions(raw);
    await runJudgeDisable(options);
    if (options.json) {
      console.log(JSON.stringify({ enabled: false }));
      return;
    }
    log(`${bold("Judge:")} ${yellow("disabled")}`);
    log(dim("  Agent files were not removed. Delete them manually if you no longer need them."));
  });

  addCommon(judge.command("status").description("Show judge configuration and installed agent files."), false).action(
    async (raw) => {
      const options = normalizeOptions(raw);
      const result = await runJudgeStatus(options);
      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }
      const enabledLabel = result.enabled ? green("enabled") : yellow("disabled");
      log(`${bold("Judge:")} ${enabledLabel}  ${dim(`trigger: ${result.trigger}`)}`);
      if (result.presentFiles.length) {
        ln();
        log(`  ${dim("Agent files present:")}`);
        for (const f of result.presentFiles) log(`    ${plus()} ${file(f)}`);
      }
      if (result.missingFiles.length) {
        ln();
        log(`  ${yellow("Agent files missing (run `akrctx judge enable`):")}`);
        for (const f of result.missingFiles) log(`    ${minus()} ${file(f)}`);
      }
      if (!result.enabled) {
        ln();
        log(`  Run ${cmd("akrctx judge enable")} to activate.`);
      }
    },
  );

  judge
    .command("snapshot")
    .description("Capture an immutable local review snapshot without changing Git state.")
    .argument("<task-id>", "task capsule ID, for example TASK-001")
    .option("--base <ref>", "base Git ref for a full snapshot", "HEAD")
    .option("--from-review <file>", "capture only changes since a verified approved snapshot review")
    .option("--json", "emit snapshot metadata for automation", false)
    .action(async (taskId: string, raw: Record<string, unknown>) => {
      const options = normalizeOptions(raw);
      const cwd = options.cwd ?? process.cwd();
      const snapshot = raw.fromReview
        ? await captureJudgeCatchUpSnapshot(cwd, taskId, String(raw.fromReview))
        : await captureJudgeSnapshot(cwd, taskId, String(raw.base));
      if (options.json) {
        console.log(JSON.stringify(snapshot, null, 2));
        return;
      }
      log(`${bold("Judge snapshot:")} ${taskId}@${snapshot.id}`);
      log(`  ${dim("candidate")} ${snapshot.candidate}`);
      log(`  ${dim("changed")}   ${snapshot.scope.changedFiles.length} file(s)`);
      if (snapshot.parent) log(`  ${dim("catch-up")}  from ${snapshot.parent.snapshotId}`);
      ln();
      log(`  ${green("✓")} ${dim("Captured without changing branch, index, stash, refs, or live files.")}`);
      log(`  ${dim("You can keep working while the judge reviews this snapshot.")}`);
    });

  judge
    .command("prune")
    .description("Preview or remove old local judge snapshots while preserving retained ancestry.")
    .option("--keep <count>", "number of newest snapshots to retain", "5")
    .option("--force", "apply the removal; without this flag only preview it", false)
    .option("--json", "emit JSON output", false)
    .action(async (raw: Record<string, unknown>) => {
      const options = normalizeOptions(raw);
      const keep = Number(raw.keep);
      const result = await pruneJudgeSnapshots(options.cwd ?? process.cwd(), {
        keep,
        dryRun: !options.force,
      });
      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }
      log(`${bold("Judge snapshots:")} ${result.dryRun ? yellow("prune preview") : green("pruned")}`);
      log(`  ${dim("retained")} ${result.kept.length}`);
      log(`  ${dim(result.dryRun ? "would remove" : "removed")} ${result.removed.length}`);
      if (result.dryRun && result.removed.length > 0) {
        log(`  ${dim("Run with --force to remove the listed obsolete snapshots.")}`);
      }
    });

  judge
    .command("current")
    .description("Compare an approved snapshot review with the current workspace.")
    .argument("<review-file>", "path to a snapshot review JSON")
    .option("--json", "emit JSON output", false)
    .action(async (reviewFile: string, raw: Record<string, unknown>) => {
      const options = normalizeOptions(raw);
      const result = await checkJudgeReviewCurrentState(options.cwd ?? process.cwd(), reviewFile);
      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }
      const label = result.status === "CURRENT" ? green(result.status) : yellow(result.status);
      log(`${bold("Judge snapshot:")} ${label}`);
      if (result.status === "CURRENT") {
        log(`  ${dim("The workspace still matches the approved snapshot.")}`);
      } else if (result.status === "NEWER_CHANGES") {
        log(`  ${dim("The approval remains valid for its snapshot; the workspace has newer changes.")}`);
        log(`  ${dim("Capture a catch-up snapshot to review only the delta.")}`);
      } else {
        log(`  ${dim("The current Git lineage differs from the approved snapshot.")}`);
      }
    });

  judge
    .command("scope")
    .description("Compute the deterministic task and code boundary a judge must review.")
    .argument("<task-id>", "task capsule ID, for example TASK-001")
    .requiredOption("--base <ref>", "base Git commit or ref")
    .option("--candidate <ref>", "candidate Git commit/ref, or WORKTREE", "WORKTREE")
    .option("--json", "emit the scope block to copy into the review record", false)
    .action(async (taskId: string, raw: Record<string, unknown>) => {
      const options = normalizeOptions(raw);
      const scope = await createJudgeScope(
        options.cwd ?? process.cwd(),
        taskId,
        raw.base as string,
        raw.candidate as string,
      );
      if (options.json) {
        console.log(JSON.stringify(scope, null, 2));
        return;
      }
      log(`${bold("Judge scope:")} ${scope.taskId}`);
      ln();
      log(`  ${dim("base")}       ${scope.base} ${dim(`(${scope.baseCommit.slice(0, 12)})`)}`);
      log(`  ${dim("candidate")}  ${scope.candidate} ${dim(`(${scope.candidateCommit.slice(0, 12)})`)}`);
      log(`  ${dim("akrctx")}     v${scope.cliVersion}`);
      log(`  ${dim("task")}       ${scope.taskDigest}`);
      log(`  ${dim("change")}     ${scope.changeDigest}`);
      log(`  ${dim("scope")}      ${scope.scopeDigest}`);
      ln();
      log(`  ${dim(`Changed files (${scope.changedFiles.length}):`)}`);
      for (const f of scope.changedFiles) log(`    ${file(f)}`);
      if (scope.excludedPaths.length) {
        ln();
        log(`  ${yellow(`Withheld by policy.json — not read, not fingerprinted (${scope.excludedPaths.length}):`)}`);
        for (const f of scope.excludedPaths) log(`    ${minus()} ${file(f)}`);
      }
      ln();
      log(`  ${dim("Run with")} ${cmd("--json")} ${dim("to emit the scope block for the review record.")}`);
    });

  judge
    .command("verify")
    .description("Verify that a judge review is APPROVED and still matches the repository.")
    .argument("<review-file>", "path to the judge review JSON")
    .option("--json", "emit JSON output", false)
    .option("--run-tests", "re-run the capsule-declared commands the record claims passed", false)
    .addHelpText(
      "after",
      [
        "",
        "Without --run-tests, a passing validation is taken from the record on trust.",
        "With it, this CLI re-executes those commands itself, fails if any fails, and",
        "fails if running them moved the reviewed boundary.",
        "",
        "Only commands declared in a fenced block under `## Validation` in the",
        "capsule's task.md are ever executed, so a review record cannot get an",
        "arbitrary command run. The capsule itself is usually written by an agent,",
        "so this moves trust from the record to task.md rather than removing it.",
        "Read task.md before using this on work you did not supervise.",
      ].join("\n"),
    )
    .action(async (reviewFile: string, raw: Record<string, unknown>) => {
      const options = normalizeOptions(raw);
      const runTests = Boolean(raw.runTests);
      const result = await verifyJudgeRecord(options.cwd ?? process.cwd(), reviewFile, { runTests });
      if (options.json) {
        console.log(JSON.stringify(result, null, 2));
      } else {
        if (result.approved) {
          log(`${bold("Judge verification:")} ${green("APPROVED and current")}`);
          log(`  ${dim(result.scopeDigest ?? "")}`);
        } else {
          log(`${bold("Judge verification:")} ${yellow("INVALID")}`);
          for (const reason of result.reasons) log(`  ${minus()} ${reason}`);
        }
        for (const notice of result.notices) log(`  ${yellow("!")} ${notice}`);
        for (const run of result.reexecuted) {
          log(`  ${run.passed ? plus() : minus()} ${dim("re-ran")} ${cmd(run.command)}`);
        }
        if (result.reexecuted.length) {
          log(`  ${dim("Commands came from the capsule's task.md `## Validation` block.")}`);
        }
        if (!runTests && result.declaredCommands.length) {
          ln();
          log(`  ${dim("Validation was taken on trust. Re-run it here with")} ${cmd("--run-tests")}${dim(".")}`);
        }
      }
      if (!result.approved) process.exitCode = 1;
    });
}
